debug: false
api_url: "https://api.suse.de/"
default_project: "openSUSE:Factory"
default_product: "openSUSE:Factory:Products:XYZ:1.1"
default_productcomposer: "/000productcompose/default.productcompose"
artifacts:
  repo_info:
    - name: "images"
      pattern: "\\b(kiwi-templates-Minimal|SL-Micro)\\b"
    - name: "product"
      pattern: "\\b(000productcompose:)\\b"
  invalid_extensions:
    - ".json"
    - ".milestone"
    - ".packages"
    - ".sha256"
    - ".asc"
    - ".report"
    - ".rpm"
    - ".verified"
  invalid_start:
    - "_"
gitea:
  reviewer: "OBS-review"
  label: "OBS:Maintained"
